// Copyright (C) 2025 Laurynas 'Deviltry' Ekekeke
// SPDX-License-Identifier: BSD-3-Clause

#pragma once

#define XY_DEAD_ZONE 40
#define XY_MAX 510

#define TRIG_DEAD_ZONE 10
#define TRIG_MAX 1000

#define MOD_ENGINE_MAIN_LEFT_PWM_FORWARD 15
#define MOD_ENGINE_MAIN_LEFT_PWM_BACKWARD 14
#define MOD_ENGINE_MAIN_RIGHT_PWM_FORWARD 13
#define MOD_ENGINE_MAIN_RIGHT_PWM_BACKWARD 12

#define MOD_TURRET_CTRL_ROTATE_PWM 16
#define MOD_TURRET_CTRL_ROTATE_DIR 17
#define MOD_TURRET_CTRL_TILT_PWM 18
#define MOD_TURRET_CTRL_TILT_DIR 19

#define MOD_LEDS_WHITE 6
#define MOD_LEDS_RED 5
